var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";f.expectedDataFileDownloads||(f.expectedDataFileDownloads=0);f.expectedDataFileDownloads++;
(()=>{var a=typeof ENVIRONMENT_IS_WASM_WORKER!="undefined"&&ENVIRONMENT_IS_WASM_WORKER;if(!(typeof ENVIRONMENT_IS_PTHREAD!="undefined"&&ENVIRONMENT_IS_PTHREAD||a)){var b=globalThis.process&&globalThis.process.versions&&globalThis.process.versions.node&&globalThis.process.type!="renderer";(async function(c){async function d(p,r){if(b){var v=require("fs").readFileSync(p);return(new Uint8Array(v)).buffer}f.dataFileDownloads||(f.dataFileDownloads={});try{var w=await fetch(p)}catch(I){throw Error(`Network Error: ${p}`,
{e:I});}if(!w.ok)throw Error(`${w.status}: ${w.url}`);v=[];r=Number(w.headers.get("Content-Length")||r);var G=0;f.setStatus&&f.setStatus("Downloading data...");for(w=w.body.getReader();;){var E;({done:E,value:K}=await w.read());if(E)break;v.push(K);G+=K.length;f.dataFileDownloads[p]={loaded:G,total:r};var K=E=0;for(var J of Object.values(f.dataFileDownloads))E+=J.loaded,K+=J.total;f.setStatus&&f.setStatus(`Downloading data... (${E}/${K})`)}p=new Uint8Array(v.map(I=>I.length).reduce((I,Z)=>I+Z,0));
J=0;for(let I of v)p.set(I,J),J+=I.length;return p.buffer}async function e(p){p.FS_createPath("/","data",!0,!0);for(var r of c.files)p.addRunDependency(`fp ${r.filename}`);p.addRunDependency("datafile_index.data");p.preloadResults||(p.preloadResults={});p.preloadResults["index.data"]={Jh:!1};m||=await l;(async function(v){if(!v)throw Error("Loading data file failed.");if(v.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+v.constructor.name);v=new Uint8Array(v);for(var w of c.files){var G=
w.filename;p.FS_createDataFile(G,null,v.subarray(w.start,w.end),!0,!0,!0);p.removeRunDependency(`fp ${G}`)}p.removeRunDependency("datafile_index.data")})(m)}typeof window==="object"?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):typeof process==="undefined"&&typeof location!=="undefined"&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var g=f.locateFile?f.locateFile("index.data",""):"index.data",
h=c.remote_package_size,l,m=f.getPreloadedPackage&&f.getPreloadedPackage(g,h);m||(l=d(g,h));f.calledRun?e(f):(f.preRun||(f.preRun=[]),f.preRun.push(e))})({files:[{filename:"/data/Archer.bmp",start:0,end:4854},{filename:"/data/Chevalier.bmp",start:4854,end:9708},{filename:"/data/Dragon.bmp",start:9708,end:14562},{filename:"/data/Eau.bmp",start:14562,end:19416},{filename:"/data/Gargouille.bmp",start:19416,end:24270},{filename:"/data/Herbe.bmp",start:24270,end:29124},{filename:"/data/Pont.bmp",start:29124,
end:33978},{filename:"/data/Terre - Copie.bmp",start:33978,end:38832},{filename:"/data/Terre.bmp",start:38832,end:43686},{filename:"/data/TourAir.bmp",start:43686,end:48540},{filename:"/data/TourRoi.bmp",start:48540,end:53394},{filename:"/data/TourSol.bmp",start:53394,end:58248}],remote_package_size:58248})}})();var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);typeof module!="undefined"&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),na,oa=!1,pa,la=a=>a.startsWith("file://");
function n(a){f.onAbort?.(a);a=`Aborted(${a})`;k(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var qa;async function ra(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==qa&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function sa(a,b){try{var c=await ra(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),n(d)}}async function ta(a){var b=qa;if(!na&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return sa(b,a)}
class ua{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var va,q,wa,t,u,x,xa,y,z,ya=a=>{for(;a.length>0;)a.shift()(f)},za=[],Aa=[],Ba=()=>{var a=f.preRun.shift();Aa.push(a)},Ca=0,Da=null,Ea=()=>{Ca--;f.monitorRunDependencies?.(Ca);if(Ca==0&&Da){var a=Da;Da=null;a()}},Fa=()=>{Ca++;f.monitorRunDependencies?.(Ca)},Ga=!0,Ha=[],A=a=>{var b=Ha[a];b||(Ha[a]=b=Ia.get(a));return b},Ka=()=>{var a=q[+Ja>>2];Ja+=4;return a},La=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");
return a},Ma=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=La(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Na=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Oa=()=>{if(ca){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>(crypto.getRandomValues(b),0)},Pa=a=>(Pa=Oa())(a),Qa=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=
d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=La(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ra=globalThis.TextDecoder&&new TextDecoder,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&Ra)return Ra.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=(e&
240)==224?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Sa=[],Ta=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},C=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(h<=127){if(c>=d)break;b[c++]=h}else if(h<=2047){if(c+1>=d)break;b[c++]=
192|h>>6;b[c++]=128|h&63}else if(h<=65535){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;g++}}b[c]=0;return c-e},Ua=a=>{var b=Array(Ta(a)+1);a=C(a,b,0,b.length);b.length=a;return b},Va=[];function Wa(a,b){Va[a]={input:[],output:[],Jf:b};Xa(a,Ya)}
var Ya={open(a){var b=Va[a.node.rdev];if(!b)throw new D(43);a.tty=b;a.seekable=!1},close(a){a.tty.Jf.fsync(a.tty)},fsync(a){a.tty.Jf.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Jf.Bg)throw new D(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Jf.Bg(a.tty)}catch(l){throw new D(29);}if(h===void 0&&e===0)throw new D(6);if(h===null||h===void 0)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Jf.ng)throw new D(60);try{for(var e=0;e<d;e++)a.tty.Jf.ng(a.tty,b[c+e])}catch(g){throw new D(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Za={Bg(){a:{if(!Sa.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}c>0&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}Sa=Ua(a)}a=Sa.shift()}return a},ng(a,b){b===null||b===10?(ma(B(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>
0&&(ma(B(a.output)),a.output=[])},dh(){return{yh:25856,Ah:5,xh:191,zh:35387,wh:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},eh(){return 0},fh(){return[24,80]}},$a={ng(a,b){b===null||b===10?(k(B(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(k(B(a.output)),a.output=[])}},F={Hf:null,If(){return F.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new D(63);F.Hf||(F.Hf={dir:{node:{Nf:F.sf.Nf,
Kf:F.sf.Kf,lookup:F.sf.lookup,Zf:F.sf.Zf,rename:F.sf.rename,unlink:F.sf.unlink,rmdir:F.sf.rmdir,readdir:F.sf.readdir,symlink:F.sf.symlink},stream:{Gf:F.rf.Gf}},file:{node:{Nf:F.sf.Nf,Kf:F.sf.Kf},stream:{Gf:F.rf.Gf,read:F.rf.read,write:F.rf.write,lg:F.rf.lg,Gg:F.rf.Gg}},link:{node:{Nf:F.sf.Nf,Kf:F.sf.Kf,readlink:F.sf.readlink},stream:{}},zg:{node:{Nf:F.sf.Nf,Kf:F.sf.Kf},stream:ab}});c=bb(a,b,c,d);H(c.mode)?(c.sf=F.Hf.dir.node,c.rf=F.Hf.dir.stream,c.uf={}):(c.mode&61440)===32768?(c.sf=F.Hf.file.node,
c.rf=F.Hf.file.stream,c.wf=0,c.uf=F.Ug??(F.Ug=new Uint8Array(0))):(c.mode&61440)===40960?(c.sf=F.Hf.link.node,c.rf=F.Hf.link.stream):(c.mode&61440)===8192&&(c.sf=F.Hf.zg.node,c.rf=F.Hf.zg.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.uf[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},sf:{Nf(a){var b={};b.dev=(a.mode&61440)===8192?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;H(a.mode)?b.size=4096:(a.mode&61440)===32768?b.size=a.wf:(a.mode&61440)===40960?b.size=a.link.length:
b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Kf(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.wf!=b&&(c=a.uf,a.uf=new Uint8Array(b),a.uf.set(c.subarray(0,Math.min(b,a.wf))),a.wf=b))},lookup(){F.cg||(F.cg=new D(44),F.cg.stack="<generic error, no stack>");throw F.cg;},Zf(a,b,c,d){return F.createNode(a,b,c,d)},rename(a,b,c){try{var d=cb(b,c)}catch(g){}if(d){if(H(a.mode))for(var e in d.uf)throw new D(55);
db(d)}delete a.parent.uf[a.name];b.uf[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.uf[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=cb(a,b),d;for(d in c.uf)throw new D(55);delete a.uf[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.uf)]},symlink(a,b,c){a=F.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if((a.mode&61440)!==40960)throw new D(28);return a.link}},rf:{read(a,b,c,d,e){if(e>=a.node.wf)return 0;d=Math.min(a.node.wf-
e,d);b.set(a.node.uf.subarray(e,e+d),c);return d},write(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(g)a.uf=b.subarray(c,c+d),a.wf=d;else if(a.wf===0&&e===0)a.uf=b.slice(c,c+d),a.wf=d;else{g=e+d;var h=a.uf.length;h>=g||(g=Math.max(g,h*(h<1048576?2:1.125)>>>0),h&&(g=Math.max(g,256)),h=a.uf.subarray(0,a.wf),a.uf=new Uint8Array(g),a.uf.set(h));a.uf.set(b.subarray(c,c+d),e);a.wf=Math.max(a.wf,e+d)}return d},Gf(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.wf);
if(b<0)throw new D(28);return b},lg(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new D(43);a=a.node.uf;if(e&2||a.buffer!==t.buffer){d=!0;n();e=void 0;if(!e)throw new D(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);t.set(a,e)}}else d=!1,e=a.byteOffset;return{Sh:e,sh:d}},Gg(a,b,c,d){F.rf.write(a,b,0,d,c,!1);return 0}}},eb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},fb=async a=>{a=await ja(a);return new Uint8Array(a)},gb=[],jb=async(a,b)=>
{typeof hb!="undefined"&&ib();for(var c of gb)if(c.canHandle(b))return c.handle(a,b);return a},kb=null,lb={},mb=[],nb=1,ob=null,pb=!1,qb=!0,D=class{name="ErrnoError";constructor(a){this.Ff=a}},rb=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},sb=class{sf={};rf={};Rf=null;constructor(a,b,c,d){a||=this;this.parent=a;this.If=a.If;this.id=nb++;this.name=b;this.mode=c;this.rdev=
d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}get hh(){return H(this.mode)}get gh(){return(this.mode&61440)===8192}};
function tb(a,b={}){if(!a)throw new D(44);b.fg??(b.fg=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(l=>!!l);for(var d=kb,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if(a[g]!==".")if(a[g]==="..")if(e=Na(e),d===d.parent){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=Ma(e+"/"+a[g]);try{d=cb(d,a[g])}catch(l){if(l?.Ff===44&&h&&b.jh)return{path:e};throw l;}!d.Rf||h&&!b.fg||(d=d.Rf.root);if((d.mode&61440)===40960&&(!h||b.eg)){if(!d.sf.readlink)throw new D(52);
d=d.sf.readlink(d);d.charAt(0)==="/"||(d=Na(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new D(32);}function ub(a){for(var b;;){if(a===a.parent)return a=a.If.Fg,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function vb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ob.length}
function db(a){var b=vb(a.parent.id,a.name);if(ob[b]===a)ob[b]=a.Pf;else for(b=ob[b];b;){if(b.Pf===a){b.Pf=a.Pf;break}b=b.Pf}}function cb(a,b){var c=H(a.mode)?(c=wb(a,"x"))?c:a.sf.lookup?0:2:54;if(c)throw new D(c);for(c=ob[vb(a.id,b)];c;c=c.Pf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.sf.lookup(a,b)}function bb(a,b,c,d){a=new sb(a,b,c,d);b=vb(a.parent.id,a.name);a.Pf=ob[b];return ob[b]=a}function H(a){return(a&61440)===16384}
function wb(a,b){return qb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function xb(a,b){if(!H(a.mode))return 54;try{return cb(a,b),20}catch(c){}return wb(a,"wx")}function yb(a){a=mb[a];if(!a)throw new D(8);return a}function zb(a,b=-1){a=Object.assign(new rb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!mb[b])break a;throw new D(33);}a.fd=b;return mb[b]=a}function Ab(a,b=-1){a=zb(a,b);a.rf?.Hh?.(a);return a}
function Bb(a,b){var c=void 0,d=c?null:a;c??=a.sf.Kf;if(!c)throw new D(63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new D(22);throw e;}}var ab={open(a){a.rf=lb[a.node.rdev].rf;a.rf.open?.(a)},Gf(){throw new D(70);}};function Xa(a,b){lb[a]={rf:b}}
function Cb(a,b){var c=b==="/";if(c&&kb)throw new D(10);if(!c&&b){var d=tb(b,{fg:!1});b=d.path;d=d.node;if(d.Rf)throw new D(10);if(!H(d.mode))throw new D(54);}b={type:a,Qh:{},Fg:b,ih:[]};a=a.If(b);a.If=b;b.root=a;c?kb=a:d&&(d.Rf=b,d.If&&d.If.ih.push(b))}function Db(a,b,c){var d=tb(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new D(28);if(a==="."||a==="..")throw new D(20);var e=xb(d,a);if(e)throw new D(e);if(!d.sf.Zf)throw new D(63);return d.sf.Zf(d,a,b,c)}
function Eb(a,b=438){return Db(a,b&4095|32768,0)}function L(a){return Db(a,16895,0)}function Fb(a,b,c){typeof c=="undefined"&&(c=b,b=438);return Db(a,b|8192,c)}function Gb(a,b){if(!Qa(a))throw new D(44);var c=tb(b,{parent:!0}).node;if(!c)throw new D(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=xb(c,b);if(d)throw new D(d);if(!c.sf.symlink)throw new D(63);c.sf.symlink(c,b,a)}
function Hb(a){var b=tb(a,{parent:!0}).node;if(!b)throw new D(44);a=a&&a.match(/([^\/]+|\/)\/*$/)[1];var c=cb(b,a);a:{try{var d=cb(b,a)}catch(g){d=g.Ff;break a}var e=wb(b,"wx");d=e?e:H(d.mode)?31:0}if(d)throw new D(d);if(!b.sf.unlink)throw new D(63);if(c.Rf)throw new D(10);b.sf.unlink(b,a);db(c)}function Ib(a,b){a=typeof a=="string"?tb(a,{eg:!0}).node:a;Bb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),Gh:void 0})}
function Jb(a,b,c=438){if(a==="")throw new D(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var g=tb(a,{eg:!(b&131072),jh:!0});d=g.node;a=g.path}g=!1;if(b&64)if(d){if(b&128)throw new D(20);}else{if(e)throw new D(31);d=Db(a,c|511,0);g=!0}if(!d)throw new D(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!H(d.mode))throw new D(54);
if(!g&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=H(d.mode)&&(e!=="r"||b&576)?31:wb(d,e)):e=44,e))throw new D(e);if(b&512&&!g){e=d;e=typeof e=="string"?tb(e,{eg:!0}).node:e;if(H(e.mode))throw new D(31);if((e.mode&61440)!==32768)throw new D(28);if(a=wb(e,"w"))throw new D(a);Bb(e,{size:0,timestamp:Date.now()})}b=zb({node:d,path:ub(d),flags:b&-131713,seekable:!0,position:0,rf:d.rf,oh:[],error:!1});b.rf.open&&b.rf.open(b);g&&Ib(d,c&511);return b}
function Kb(a){if(a.fd===null)throw new D(8);a.ig&&(a.ig=null);try{a.rf.close&&a.rf.close(a)}catch(b){throw b;}finally{mb[a.fd]=null}a.fd=null}function Lb(a,b,c){if(a.fd===null)throw new D(8);if(!a.seekable||!a.rf.Gf)throw new D(70);if(c!=0&&c!=1&&c!=2)throw new D(28);a.position=a.rf.Gf(a,b,c);a.oh=[]}
function Mb(a,b,c,d,e,g){if(d<0||e<0)throw new D(28);if(a.fd===null)throw new D(8);if((a.flags&2097155)===0)throw new D(8);if(H(a.node.mode))throw new D(31);if(!a.rf.write)throw new D(28);a.seekable&&a.flags&1024&&Lb(a,0,2);var h=typeof e!="undefined";if(!h)e=a.position;else if(!a.seekable)throw new D(70);b=a.rf.write(a,b,c,d,e,g);h||(a.position+=b);return b}
function Nb(a,b){a=typeof a=="string"?a:ub(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ma(a+"/"+c);try{L(d)}catch(e){if(e.Ff!=20)throw e;}a=d}}return d}function Ob(a,b,c,d){a=Ma((typeof a=="string"?a:ub(a))+"/"+b);return Eb(a,eb(c,d))}function Pb(a,b,c,d,e,g){var h=b;a&&(a=typeof a=="string"?a:ub(a),h=b?Ma(a+"/"+b):a);a=eb(d,e);h=Eb(h,a);c&&(typeof c=="string"&&(c=Ua(c)),c.subarray||(c=new Uint8Array(c)),Ib(h,a|146),b=Jb(h,577),Mb(b,c,0,c.length,0,g),Kb(b),Ib(h,a))}
function Qb(a,b,c,d){a=Ma((typeof a=="string"?a:ub(a))+"/"+b);b=eb(!!c,!!d);Qb.Dg??(Qb.Dg=64);var e=Qb.Dg++<<8|0;Xa(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,l,m){for(var p=0,r=0;r<m;r++){try{var v=c()}catch(w){throw new D(29);}if(v===void 0&&p===0)throw new D(6);if(v===null||v===void 0)break;p++;h[l+r]=v}p&&(g.node.atime=Date.now());return p},write(g,h,l,m){for(var p=0;p<m;p++)try{d(h[l+p])}catch(r){throw new D(29);}m&&(g.node.mtime=g.node.ctime=Date.now());return p}});
return Fb(a,b,e)}function Rb(a){if(!(a.gh||a.hh||a.link||a.uf))if(globalThis.XMLHttpRequest)n("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.uf=ka(a.url)}catch(b){throw new D(29);}}
function Sb(a,b,c,d,e){class g{rg=!1;Of=[];pg=void 0;Mg=0;Jg=0;get(p){if(!(p>this.length-1||p<0)){var r=p%this.chunkSize;return this.pg(p/this.chunkSize|0)[r]}}rh(p){this.pg=p}Ng(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);p.status>=200&&p.status<300||p.status===304||n("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),v,w=(v=p.getResponseHeader("Accept-Ranges"))&&v==="bytes";p=(v=p.getResponseHeader("Content-Encoding"))&&v==="gzip";var G=
1048576;w||(G=r);var E=this;E.rh(K=>{var J=K*G,I=(K+1)*G-1;I=Math.min(I,r-1);if(typeof E.Of[K]=="undefined"){var Z=E.Of;J>I&&n(`invalid range (${J}, ${I}) or no bytes requested!`);I>r-1&&n(`only ${r} bytes available! programmer error!`);var N=new XMLHttpRequest;N.open("GET",c,!1);r!==G&&N.setRequestHeader("Range","bytes="+J+"-"+I);N.responseType="arraybuffer";N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);N.status>=200&&N.status<300||N.status===304||n("Couldn't load "+
c+". Status: "+N.status);J=N.response!==void 0?new Uint8Array(N.response||[]):Ua(N.responseText??"");Z[K]=J}typeof E.Of[K]=="undefined"&&n("doXHR failed!");return E.Of[K]});if(p||!r)G=r=1,G=r=this.pg(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.Mg=r;this.Jg=G;this.rg=!0}get length(){this.rg||this.Ng();return this.Mg}get chunkSize(){this.rg||this.Ng();return this.Jg}}if(globalThis.XMLHttpRequest){ba||n("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var h=new g;var l=void 0}else l=c,h=void 0;var m=Ob(a,b,d,e);h?m.uf=h:l&&(m.uf=null,m.url=l);Object.defineProperties(m,{wf:{get:function(){return this.uf.length}}});a={};for(let [p,r]of Object.entries(m.rf))a[p]=(...v)=>{Rb(m);return r(...v)};a.read=(p,r,v,w,G)=>{Rb(m);p=p.node.uf;if(G>=p.length)r=0;else{w=Math.min(p.length-G,w);if(p.slice)for(var E=0;E<w;E++)r[v+E]=p[G+E];else for(E=0;E<w;E++)r[v+E]=p.get(G+E);r=w}return r};a.lg=()=>{Rb(m);n();throw new D(48);};m.rf=a;return m}
var Tb={},Ub=(a,b)=>a?B(z,a,b):"",Ja=void 0,Vb=0,Wb={},Xb=a=>{a instanceof ua||a=="unwind"||fa(1,a)},Yb=a=>{pa=a;Ga||Vb>0||(f.onExit?.(a),oa=!0);fa(a,new ua(a))},Zb=()=>{if(!(Ga||Vb>0))try{var a=pa;pa=a;Yb(a)}catch(b){Xb(b)}},$b=a=>{if(!oa)try{a()}catch(b){Xb(b)}finally{Zb()}};function ac(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var bc=a=>{setTimeout(()=>{$b(a)},1E4)},cc=!1,dc=!1,ec=[];
function ib(){function a(){dc=document.pointerLockElement===f.canvas}if(!fc){fc=!0;gb.push({canHandle:c=>!f.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:hc(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:hc(d)}));var g=URL.createObjectURL(e);return new Promise((h,l)=>{var m=new Image;m.onload=()=>{var p=document.createElement("canvas");p.width=m.width;p.height=m.height;p.getContext("2d").drawImage(m,0,0);URL.revokeObjectURL(g);
h(c)};m.onerror=()=>{k(`Image ${g} could not be decoded`);l()};m.src=g})}});gb.push({canHandle:c=>!f.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function g(){h||(h=!0,e(c))}var h=!1,l=new Blob([c],{type:hc(d)});l=URL.createObjectURL(l);var m=new Audio;m.addEventListener("canplaythrough",()=>g(m),!1);m.onerror=()=>{if(!h){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var p="data:audio/x-"+d.slice(-3)+";base64,",
r="",v=0,w=0,G=0;G<c.length;G++)for(v=v<<8|c[G],w+=8;w>=6;){var E=v>>w-6&63;w-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[E]}w==2?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&3)<<4],r+="=="):w==4&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&15)<<2],r+="=");m.src=p+r;g(m)}};m.src=l;bc(()=>{g(m)})})});var b=f.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",
c=>{!dc&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}function ic(a,b,c,d){if(b&&f.ctx&&a==f.canvas)return f.ctx;var e;if(b){var g={antialias:!1,alpha:!1,Eg:2};if(d)for(var h in d)g[h]=d[h];if(typeof jc!="undefined"&&(e=kc(a,g)))var l=lc[e].Lf}else l=a.getContext("2d");if(!l)return null;c&&(f.ctx=l,b&&mc(e),ec.forEach(m=>m()),ib());return l}var nc=!1,oc=void 0,pc=void 0;
function qc(){if(!cc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}function hc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var rc=[];function sc(){var a=f.canvas;rc.forEach(b=>b(a.width,a.height))}
function tc(a){if(b&&c)a.qh=b,a.Zg=c;else{var b=a.qh;var c=a.Zg}var d=b,e=c;f.forcedAspectRatio>0&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if(ac()===a.parentNode&&typeof screen!="undefined"){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*g)}pc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),typeof a.style!="undefined"&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=
b),a.height!=c&&(a.height=c),typeof a.style!="undefined"&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var hb={},fc,M=12288,uc=!1,vc=0,wc=0,xc=0,O={alpha:!1,depth:!1,stencil:!1,antialias:!1},yc={},zc,P,Ac=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");return a.getSupportedExtensions()?.filter(c=>
b.includes(c))??[]},Bc=1,Cc=[],Q=[],Dc=[],Ec=[],Fc=[],R=[],Gc=[],lc=[],Hc=[],S=[],Ic=[],Jc=[],Kc={},Lc={},Mc=4,Nc=0,Oc=a=>{for(var b=Bc++,c=a.length;c<b;c++)a[c]=null;return b},Pc=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=P[c](),h=g&&Oc(d);g?(g.name=h,d[h]=g):T||=1282;q[b+e*4>>2]=h}},kc=(a,b)=>{a.Of||(a.Of=a.getContext,a.getContext=function(d,e){e=a.Of(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Qc(c,b):0},Qc=(a,b)=>{var c=Oc(lc),d={handle:c,
attributes:b,version:b.Eg,Lf:a};a.canvas&&(a.canvas.Qf=d);lc[c]=d;if(typeof b.Vg=="undefined"||b.Vg)if((a=d)||(a=Rc),!a.ah){a.ah=!0;b=a.Lf;b.Ph=b.getExtension("WEBGL_multi_draw");b.Xg=b.getExtension("EXT_polygon_offset_clamp");b.Wg=b.getExtension("EXT_clip_control");b.ph=b.getExtension("WEBGL_polygon_mode");b.Fh=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Nh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");a.version>=2&&(b.Cf=b.getExtension("EXT_disjoint_timer_query_webgl2"));
if(a.version<2||!b.Cf)b.Cf=b.getExtension("EXT_disjoint_timer_query");for(var e of Ac(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},mc=a=>{Rc=lc[a];f.ctx=P=Rc?.Lf},jc={},T,Rc,Sc=a=>{var b=Ta(a)+1,c=U(b);c&&C(a,z,c,b);return c},gd=a=>{function b(){return c<Tc?(Zb(),!1):!0}Uc=a;var c=Tc;Vc=!1;Wc=function(){if(!oa)if(Xc.length>0){var d=Xc.shift();d.Kh(d.th);if(Yc){var e=Yc,g=e%1==0?e-1:Math.floor(e);Yc=d.Ch?g:(8*e+(g+.5))/9}f.setStatus&&(d=f.statusMessage||"Please wait...",
e=Yc??0,g=Zc.Ih??0,e?e<g?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(d):f.setStatus(""));b()&&setTimeout(Wc,0)}else if(b())if($c=$c+1|0,ad==1&&bd>1&&$c%bd!=0)cd();else{ad==0&&(dd=performance.now());a:if(!oa){for(d of ed)if(d()===!1)break a;$b(a);for(e of fd)e()}b()&&cd()}}},Vc=!1,cd=null,Tc=0,Uc=null,ad=0,bd=0,$c=0,Xc=[],ed=[],fd=[];function hd(){cd=null;Tc++}var jd=0;
function kd(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(jd===0)jd=b+1E3/60;else for(;b+2>=jd;)jd+=1E3/60;setTimeout(a,Math.max(jd-b,0))}}
var Zc={},Wc,Yc,dd,ld,md=(a,b)=>{ad=a;bd=b;if(Uc)if(Vc||=!0,a==0)cd=function(){setTimeout(Wc,Math.max(0,dd+b-performance.now())|0)};else if(a==1)cd=function(){kd(Wc)};else{if(!ld)if(globalThis.scheduler)ld=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)ld=setImmediate;else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);ld=d=>{c.push(d);ba?postMessage("setimmediate"):postMessage("setimmediate","*")}}cd=function(){ld(Wc)}}},
nd=[],od=(a,b)=>{nd.length=0;for(var c;c=z[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;nd.push(c==112?y[b>>2]:c==106?wa[b>>3]:c==105?q[b>>2]:x[b>>3]);b+=d?8:4}return nd};function pd(a){var b=V.yf[a];b.target.removeEventListener(b.vf,b.Ag,b.Af);V.yf.splice(a,1)}function qd(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var l in g)if(g[l]!=h[l])return!1;return!0}for(var e of V.Mf)if(e.qg==a&&d(e.xg,c))return;V.Mf.push({qg:a,Ig:b,xg:c});V.Mf.sort((g,h)=>g.Ig-h.Ig)}
function rd(a){V.Mf=V.Mf.filter(b=>b.qg!=a)}function sd(){return navigator.userActivation?navigator.userActivation.isActive:V.jg&&V.Pg.Tf}function td(){if(sd()){var a=V.Mf;V.Mf=[];for(var b of a)b.qg(...b.xg)}}function W(a){if(!a.target)return-4;if(a.xf)a.Ag=function(c){++V.jg;V.Pg=a;td();a.Df(c);td();--V.jg},a.target.addEventListener(a.vf,a.Ag,a.Af),V.yf.push(a);else for(var b=0;b<V.yf.length;++b)V.yf[b].target==a.target&&V.yf[b].vf==a.vf&&pd(b--);return 0}
function ud(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var V={uh:0,hg:0,kg:0,$f:0,wg:0,tg:0,dg:0,Eh:0,Rh:0,Dh:0,gg:0,mg:0,vg:0,sg:0,Th(){for(;V.yf.length;)pd(V.yf.length-1);V.Mf=[]},jg:0,Mf:[],yf:[],mh:(a,b)=>{for(var c=0;c<V.yf.length;++c)V.yf[c].target!=a||b&&b!=V.yf[c].vf||pd(c--)},Uh(a){var b=!1;for(let c=0;c<V.yf.length;++c){let d=V.yf[c];d.target===a.target&&d.zf===a.zf&&d.xf===a.xf&&d.Bf===a.Bf&&(pd(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},vd=[0,globalThis.document??0,globalThis.window??
0],X=a=>{a=a>2?a?B(z,a):"":a;return vd[a]||globalThis.document?.querySelector(a)},xd=a=>{var b=Ta(a)+1,c=wd(b);C(a,z,c,b);return c},Ad=a=>{var b=yd(),c=wd(8),d=c+4;a=xd(a.id);if(a=X(a))q[c>>2]=a.width,q[d>>2]=a.height;c=[q[c>>2],q[d>>2]];zd(b);return c},Bd=(a,b,c)=>{a=X(a);if(!a)return-4;a.width=b;a.height=c;return 0},Cd=(a,b,c)=>{if(a.Bh){var d=yd();a=xd(a.id);Bd(a,b,c);zd(d)}else a.width=b,a.height=c},Dd={},Ed=a=>{function b(){ac()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),Cd(a,d,e),a.style.width=g,a.style.height=h,a.style.backgroundColor=l,m||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=m,a.style.paddingLeft=p,a.style.paddingRight=r,a.style.paddingTop=v,a.style.paddingBottom=w,a.style.marginLeft=G,a.style.marginRight=E,a.style.marginTop=K,a.style.marginBottom=J,document.body.style.margin=I,document.documentElement.style.overflow=Z,document.body.scroll=N,a.style.imageRendering=re,a.Qf&&a.Qf.Lf.viewport(0,0,d,e),Dd.Uf&&A(Dd.Uf)(37,
0,Dd.yg))}var c=Ad(a),d=c[0],e=c[1],g=a.style.width,h=a.style.height,l=a.style.backgroundColor,m=document.body.style.backgroundColor,p=a.style.paddingLeft,r=a.style.paddingRight,v=a.style.paddingTop,w=a.style.paddingBottom,G=a.style.marginLeft,E=a.style.marginRight,K=a.style.marginTop,J=a.style.marginBottom,I=document.body.style.margin,Z=document.documentElement.style.overflow,N=document.body.scroll,re=a.style.imageRendering;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},Fd=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Gd=a=>vd.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},Hd=(a,b)=>{if(b.og!=0||b.ag!=0){Ed(a);var c=b.nh?innerWidth:screen.width,d=b.nh?innerHeight:screen.height,e=Gd(a),g=e.width;e=e.height;var h=Ad(a),l=h[0];h=h[1];b.og==3?(Fd(a,(d-e)/2,(c-g)/2),c=g,d=e):b.og==2&&(c*h<l*d?(g=h*c/l,Fd(a,(d-g)/2,0),d=g):(g=l*d/h,Fd(a,0,(c-g)/2),c=g));var m;(m=a.style).backgroundColor||(m.backgroundColor=
"black");let p;(p=document.body.style).backgroundColor||(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.Yg==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");m=b.ag==2?devicePixelRatio:1;b.ag!=0&&(c=c*m|0,d=d*m|0,Cd(a,c,d),a.Qf&&a.Qf.Lf.viewport(0,
0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return V.fullscreenEnabled()?-3:-1;Dd=b;b.Uf&&A(b.Uf)(37,0,b.yg);return 0},Id=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Jd=(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},Kd=[],Ld=(a,b)=>{for(var c=Kd[a],d=0;d<a;d++)c[d]=q[b+d*4>>2];P.drawBuffers(c)},Md=(a,b,c,d,e)=>{P.drawElementsInstanced(a,
b,c,d,e)},Nd=(a,b,c,d,e,g,h,l)=>{b=Q[b];if(a=P[a](b,c))d=l&&C(a.name,z,l,d),e&&(q[e>>2]=d),g&&(q[g>>2]=a.size),h&&(q[h>>2]=a.type)},Od=(a,b)=>{y[a>>2]=b;y[a+4>>2]=(b-y[a>>2])/4294967296},Pd=()=>{var a=Ac(P);return a=a.concat(a.map(b=>"GL_"+b))},Qd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(T||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=P.getParameter(34467);d=e?e.length:0;break;case 33309:if(Rc.version<2){T||=1282;return}d=Pd().length;break;
case 33307:case 33308:if(Rc.version<2){T||=1280;return}d=a==33307?3:0}if(d===void 0)switch(e=P.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:T||=1280;return}else{if(e instanceof
Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:q[b+a*4>>2]=e[a];break;case 2:u[b+a*4>>2]=e[a];break;case 4:t[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){T||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:Od(b,
d);break;case 0:q[b>>2]=d;break;case 2:u[b>>2]=d;break;case 4:t[b]=d?1:0}}else T||=1281},Rd=(a,b,c,d)=>{if(c){b=P.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(b===null)switch(a){case 35983:case 35368:a=0;break;default:T||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{T||=1280;return}break;default:T||=1280;return}switch(d){case 1:Od(c,a);break;case 0:q[c>>2]=a;break;case 2:u[c>>2]=a;break;case 4:t[c]=a?1:0;break;default:n("internal emscriptenWebGLGetIndexed() error, bad type: "+
d)}}else T||=1281},Sd=(a,b,c)=>{if(c){a=Hc[a];b=Rc.version<2?P.Cf.getQueryObjectEXT(a,b):P.getQueryParameter(a,b);var d;typeof b=="boolean"?d=b?1:0:d=b;Od(c,d)}else T||=1281},Td=(a,b,c)=>{if(c){a=P.Cf.getQueryObjectEXT(Hc[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;q[c>>2]=d}else T||=1281},Ud=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),Vd=a=>{var b=a.Sf,c=a.Lg,d;if(!b){a.Sf=b={};a.Kg={};var e=P.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=P.getActiveUniform(a,d);var h=g.name;g=g.size;var l=Ud(h);
l=l>0?h.slice(0,l):h;var m=a.ug;a.ug+=g;c[l]=[g,m];for(h=0;h<g;++h)b[m]=h,a.Kg[m++]=l}}},Y=(a,b)=>{if(a){var c=a.Sf[b];typeof c=="number"&&(a.Sf[b]=c=P.getUniformLocation(a,a.Kg[b]+(c>0?`[${c}]`:"")));return c}T||=1282},Wd=(a,b,c,d)=>{if(c)if(a=Q[a],Vd(a),a=P.getUniform(a,Y(a,b)),typeof a=="number"||typeof a=="boolean")switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+b*4>>2]=a[b];break;case 2:u[c+b*4>>2]=a[b]}else T||=1281},Xd=(a,b,c,d)=>{if(c)if(a=
P.getVertexAttrib(a,b),b==34975)q[c>>2]=a&&a.name;else if(typeof a=="number"||typeof a=="boolean")switch(d){case 0:q[c>>2]=a;break;case 2:u[c>>2]=a;break;case 5:q[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+b*4>>2]=a[b];break;case 2:u[c+b*4>>2]=a[b];break;case 5:q[c+b*4>>2]=Math.fround(a[b])}else T||=1281},Yd=(a,b,c)=>{Xd(a,b,c,0)},Zd=a=>{a-=5120;return a==0?t:a==1?z:a==2?va:a==4?q:a==6?u:a==5||a==28922||a==28520||a==30779||a==30782?y:xa},$d=(a,b,c,d,e)=>{a=Zd(a);b=d*(({5:3,
6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT*(Nc||c)+Mc-1&-Mc);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},ae=(a,b)=>{P.vertexAttribDivisor(a,b)},be=(a,b)=>{if(!V.fullscreenEnabled())return-1;a=X(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?sd()?Hd(a,b):b.Tg?(qd(Hd,1,[a,b]),1):-2:-3:-4},ce=(a,b)=>{var c={target:X(2),vf:"beforeunload",zf:28,Bf:a,xf:b,Df:d=>{var e=A(b)(28,0,a);e&&=e?B(z,
e):"";if(e)return d.preventDefault(),d.returnValue=e},Af:!0};return W(c)},de=(a,b,c,d,e,g)=>{V.dg||(V.dg=U(256));a={target:X(a),vf:g,zf:e,Bf:b,xf:d,Df:h=>{var l=h.target.id??"",m=V.dg;C(ud(h.target),z,m+0,128);C(l,z,m+128,128);A(d)(e,m,b)&&h.preventDefault()},Af:c};return W(a)},ee=(a,b,c,d,e)=>{V.gg||(V.gg=U(276));return W({target:a,vf:e,zf:19,Bf:b,xf:d,Df:g=>{var h=V.gg,l=ac(),m=!!l;t[h]=m;t[h+1]=V.fullscreenEnabled();var p=m?l:V.kh,r=p?.id??"";C(ud(p),z,h+2,128);C(r,z,h+130,128);q[h+260>>2]=p?.clientWidth??
0;q[h+264>>2]=p?.clientHeight??0;q[h+268>>2]=screen.width;q[h+272>>2]=screen.height;m&&(V.kh=l);A(d)(19,h,b)&&g.preventDefault()},Af:c})},fe=(a,b,c,d,e)=>{V.hg||(V.hg=U(1240));b={target:X(2),Tf:!0,vf:e,zf:d,Bf:a,xf:c,Df:g=>{var h=V.hg,l=g.gamepad;x[h>>3]=l.timestamp;for(var m=0;m<l.axes.length;++m)x[h+m*8+16>>3]=l.axes[m];for(m=0;m<l.buttons.length;++m)x[h+m*8+528>>3]=typeof l.buttons[m]=="object"?l.buttons[m].value:l.buttons[m];for(m=0;m<l.buttons.length;++m)t[h+m+1040]=typeof l.buttons[m]=="object"?
l.buttons[m].pressed:l.buttons[m]==1;t[h+1104]=l.connected;q[h+1108>>2]=l.index;q[h+8>>2]=l.axes.length;q[h+12>>2]=l.buttons.length;C(l.id,z,h+1112,64);C(l.mapping,z,h+1176,64);A(c)(d,h,a)&&g.preventDefault()},Af:b};return W(b)},ge=()=>{try{if(navigator.getGamepads)return(V.Lh=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},he=(a,b,c,d,e,g)=>{V.kg||(V.kg=U(160));a={target:X(a),vf:g,zf:e,Bf:b,xf:d,Df:h=>{var l=V.kg;x[l>>3]=h.timeStamp;var m=l>>2;q[m+2]=h.location;t[l+12]=
h.ctrlKey;t[l+13]=h.shiftKey;t[l+14]=h.altKey;t[l+15]=h.metaKey;t[l+16]=h.repeat;q[m+5]=h.charCode;q[m+6]=h.keyCode;q[m+7]=h.which;C(h.key??"",z,l+32,32);C(h.code??"",z,l+64,32);C(h.char??"",z,l+96,32);C(h.locale??"",z,l+128,32);A(d)(e,l,b)&&h.preventDefault()},Af:c};return W(a)},ie=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;q[d+2]=b.screenX;q[d+3]=b.screenY;q[d+4]=b.clientX;q[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;va[d*2+14]=b.button;va[d*2+15]=b.buttons;
q[d+8]=b.movementX;q[d+9]=b.movementY;a=Gd(c);q[d+10]=b.clientX-(a.left|0);q[d+11]=b.clientY-(a.top|0)},je=(a,b,c,d,e,g)=>{V.$f||(V.$f=U(64));a=X(a);return W({target:a,Tf:g!="mousemove"&&g!="mouseenter"&&g!="mouseleave",vf:g,zf:e,Bf:b,xf:d,Df:h=>{ie(V.$f,h,a);A(d)(e,V.$f,b)&&h.preventDefault()},Af:c})},ke=(a,b,c,d)=>{V.mg||(V.mg=U(257));return W({target:a,vf:"pointerlockchange",zf:20,Bf:b,xf:d,Df:e=>{var g=V.mg,h=document.pointerLockElement;t[g]=!!h;var l=h?.id??"";C(ud(h),z,g+1,128);C(l,z,g+129,
128);A(d)(20,g,b)&&e.preventDefault()},Af:c})},le=(a,b,c,d)=>{V.tg||(V.tg=U(36));a=X(a);return W({target:a,vf:"resize",zf:10,Bf:b,xf:d,Df:e=>{if(e.target==a){var g=document.body;if(g){var h=V.tg;q[h>>2]=0;q[h+4>>2]=g.clientWidth;q[h+8>>2]=g.clientHeight;q[h+12>>2]=innerWidth;q[h+16>>2]=innerHeight;q[h+20>>2]=outerWidth;q[h+24>>2]=outerHeight;q[h+28>>2]=pageXOffset|0;q[h+32>>2]=pageYOffset|0;A(d)(10,h,b)&&e.preventDefault()}}},Af:c})},me=(a,b,c,d,e,g)=>{V.sg||(V.sg=U(1552));a=X(a);return W({target:a,
Tf:g=="touchstart"||g=="touchend",vf:g,zf:e,Bf:b,xf:d,Df:h=>{var l={},m=h.touches;for(var p of m)p.Cg=p.Hg=0,l[p.identifier]=p;for(var r of h.changedTouches)r.Cg=1,l[r.identifier]=r;for(var v of h.targetTouches)l[v.identifier].Hg=1;m=V.sg;x[m>>3]=h.timeStamp;t[m+12]=h.ctrlKey;t[m+13]=h.shiftKey;t[m+14]=h.altKey;t[m+15]=h.metaKey;p=m+16;r=Gd(a);v=0;for(let w of Object.values(l))if(l=p>>2,q[l]=w.identifier,q[l+1]=w.screenX,q[l+2]=w.screenY,q[l+3]=w.clientX,q[l+4]=w.clientY,q[l+5]=w.pageX,q[l+6]=w.pageY,
t[p+28]=w.Cg,t[p+29]=w.Hg,q[l+8]=w.clientX-(r.left|0),q[l+9]=w.clientY-(r.top|0),p+=48,++v>31)break;q[m+8>>2]=v;A(d)(e,m,b)&&h.preventDefault()},Af:c})},ne=(a,b,c)=>{var d=vd[1];V.vg||(V.vg=U(8));return W({target:d,vf:"visibilitychange",zf:21,Bf:a,xf:c,Df:e=>{var g=V.vg,h=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);t[g]=document.hidden;q[g+4>>2]=h;A(c)(21,g,a)&&e.preventDefault()},Af:b})},oe=(a,b,c,d)=>{V.wg||(V.wg=U(96));return W({target:a,Tf:!0,vf:"wheel",zf:9,
Bf:b,xf:d,Df:e=>{var g=V.wg;ie(g,e,a);x[g+64>>3]=e.deltaX;x[g+72>>3]=e.deltaY;x[g+80>>3]=e.deltaZ;q[g+88>>2]=e.deltaMode;A(d)(9,g,b)&&e.preventDefault()},Af:c})},pe={},se=()=>{if(!qe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea},b;for(b in pe)pe[b]===void 0?delete a[b]:a[b]=pe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);qe=c}return qe},qe;ob=Array(4096);Cb(F,"/");L("/tmp");L("/home");L("/home/web_user");
(function(){L("/dev");Xa(259,{read:()=>0,write:(d,e,g,h)=>h,Gf:()=>0});Fb("/dev/null",259);Wa(1280,Za);Wa(1536,$a);Fb("/dev/tty",1280);Fb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(Pa(a),b=a.byteLength);return a[--b]};Qb("/dev","random",c);Qb("/dev","urandom",c);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");Cb({If(){var b=bb(a,"fd",16895,73);b.rf={Gf:F.rf.Gf};b.sf={lookup(c,d){c=+d;var e=yb(c);c={parent:null,If:{Fg:"fake"},sf:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(mb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();f.requestAnimationFrame=kd;f.pauseMainLoop=hd;f.resumeMainLoop=function(){Tc++;var a=ad,b=bd,c=Uc;Uc=null;gd(c);md(a,b);cd()};f.preMainLoop&&ed.push(f.preMainLoop);
f.postMainLoop&&fd.push(f.postMainLoop);for(let a=0;a<32;++a)Kd.push(Array(a));f.noExitRuntime&&(Ga=f.noExitRuntime);f.preloadPlugins&&(gb=f.preloadPlugins);f.print&&(ma=f.print);f.printErr&&(k=f.printErr);f.wasmBinary&&(na=f.wasmBinary);f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);if(f.preInit)for(typeof f.preInit=="function"&&(f.preInit=[f.preInit]);f.preInit.length>0;)f.preInit.shift()();f.addRunDependency=Fa;f.removeRunDependency=Ea;
f.requestFullscreen=function(a,b){function c(){cc=!1;var g=d.parentNode;ac()===g?(d.exitFullscreen=qc,oc&&d.requestPointerLock(),cc=!0,pc?(typeof SDL!="undefined"&&(q[SDL.screen>>2]=y[SDL.screen>>2]|8388608),tc(f.canvas),sc()):tc(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),pc?(typeof SDL!="undefined"&&(q[SDL.screen>>2]=y[SDL.screen>>2]&-8388609),tc(f.canvas),sc()):tc(d));f.onFullScreen?.(cc);f.onFullscreen?.(cc)}oc=a;pc=b;typeof oc=="undefined"&&(oc=!0);typeof pc=="undefined"&&
(pc=!1);var d=f.canvas;nc||(nc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):
null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};f.createContext=ic;f.FS_preloadFile=async(a,b,c,d,e,g,h,l)=>{var m=b?Qa(Ma(a+"/"+b)):a,p=`cp ${m}`;Fa(p);try{var r=c;typeof c=="string"&&(r=await fb(c));r=await jb(r,m);l?.();g||Pb(a,b,r,d,e,h)}finally{Ea(p)}};f.FS_unlink=(...a)=>Hb(...a);f.FS_createPath=(...a)=>Nb(...a);f.FS_createDevice=(...a)=>Qb(...a);f.FS_createDataFile=(...a)=>Pb(...a);f.FS_createLazyFile=(...a)=>Sb(...a);
var te={56932:a=>{a=(a?B(z,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");a===null&&(a="i");return a.length===1?a.charCodeAt(0):-1},57147:()=>window.innerWidth,57177:()=>window.innerHeight,57208:(a,b,c)=>{f.SDL2||(f.SDL2={});var d=f.SDL2;d.Og!==f.canvas&&(d.Vf=ic(f.canvas,!1,!0),d.Og=f.canvas);if(d.w!==a||d.h!==b||d.$g!==d.Vf)d.image=d.Vf.createImageData(a,b),d.w=a,d.h=b,d.$g=d.Vf;a=d.image.data;b=c/4;var e=0;if(typeof CanvasPixelArray!=="undefined"&&a instanceof CanvasPixelArray)for(c=
a.length;e<c;){var g=q[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.Rg!==a&&(d.Qg=new Int32Array(a.buffer),d.Sg=new Uint8Array(a.buffer),d.Rg=a),a=d.Qg,c=a.length,a.set(q.subarray(b,b+c)),a=d.Sg,b=3,e=b+4*c,c%8==0)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Vf.putImageData(d.image,0,0)},58674:(a,b,c,d,e)=>{var g=document.createElement("canvas");
g.width=a;g.height=b;var h=g.getContext("2d");a=h.createImageData(a,b);b=a.data;e/=4;var l=0,m;if(typeof CanvasPixelArray!=="undefined"&&b instanceof CanvasPixelArray)for(m=b.length;l<m;){var p=q[e];b[l]=p&255;b[l+1]=p>>8&255;b[l+2]=p>>16&255;b[l+3]=p>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(q.subarray(e,e+m));h.putImageData(a,0,0);c=c===0&&d===0?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=U(c.length+1);C(c,z,d,c.length+1);return d},59662:a=>
{f.canvas&&(f.canvas.style.cursor=a?B(z,a):"")},59745:()=>{f.canvas&&(f.canvas.style.cursor="none")}},ue,U,ve,zd,wd,yd,we,Ia,xe={Ga:(a,b)=>A(a)(b),E:function(a,b,c){Ja=c;try{var d=yb(a);switch(b){case 0:var e=Ka();if(e<0)break;for(;mb[e];)e++;return Ab(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ka(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Ka(),va[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(g){if(typeof Tb=="undefined"||g.name!=="ErrnoError")throw g;return-g.Ff}},
Pa:function(a,b,c){Ja=c;try{var d=yb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Jf.dh){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ka();q[e>>2]=25856;q[e+4>>2]=5;q[e+8>>2]=191;q[e+12>>2]=35387;for(var g=0;g<32;g++)t[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Jf.eh)for(e=Ka(),a=[],g=0;g<32;g++)a.push(t[e+g+17]);return 0;case 21519:if(!d.tty)return-59;
e=Ka();return q[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=Ka();if(!d.rf.bh)throw new D(59);return d.rf.bh(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Jf.fh&&(g=[24,80],e=Ka(),va[e>>1]=g[0],va[e+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if(typeof Tb=="undefined"||h.name!=="ErrnoError")throw h;return-h.Ff}},Qa:function(a,b,c,d){Ja=d;try{b=b?B(z,b):"";var e=b;if(e.charAt(0)==="/")b=e;else{var g=a===-100?"/":yb(a).path;
if(e.length==0)throw new D(44);b=g+"/"+e}var h=d?Ka():0;c&64&&(h&=-19);return Jb(b,c,h).fd}catch(l){if(typeof Tb=="undefined"||l.name!=="ErrnoError")throw l;return-l.Ff}},Ja:()=>n(""),Ia:()=>{Ga=!1;Vb=0},Ea:(a,b)=>{Wb[a]&&(clearTimeout(Wb[a].id),delete Wb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Wb[a];$b(()=>ve(a,performance.now()))},b);Wb[a]={id:c,Vh:b};return 0},Tc:a=>{if(a==12448)return M=12288,1;M=12300;return 0},ef:(a,b,c,d,e)=>{if(a!=62E3)M=12296,c=0;else{if(b)for(;;){a=q[b>>2];if(a==
12321)O.alpha=q[b+4>>2]>0;else if(a==12325)O.depth=q[b+4>>2]>0;else if(a==12326)O.stencil=q[b+4>>2]>0;else if(a==12337)a=q[b+4>>2],O.antialias=a>0;else if(a==12338)a=q[b+4>>2],O.antialias=a==1;else if(a==12544)O.Mh=q[b+4>>2]!=12547;else if(a==12344)break;b+=8}c&&d||e?(e&&(q[e>>2]=1),c&&d>0&&(y[c>>2]=62002),M=12288,c=1):(M=12300,c=0)}return c},Ke:(a,b,c,d)=>{if(a!=62E3)return M=12296,0;for(a=1;;){b=q[d>>2];if(b==12440)a=q[d+4>>2];else if(b==12344)break;else return M=12292,0;d+=8}if(a<2||a>3)return M=
12293,0;O.Eg=a-1;O.Oh=0;zc=kc(f.canvas,O);if(zc!=0)return M=12288,mc(zc),ec.forEach(e=>e()),mc(null),62004;M=12297;return 0},oe:(a,b)=>{if(a!=62E3)return M=12296,0;if(b!=62002)return M=12293,0;M=12288;return 62006},ze:(a,b)=>{if(a!=62E3)return M=12296,0;if(b!=62004)return M=12294,0;a=zc;Rc===lc[a]&&(Rc=null);typeof V=="object"&&V.mh(lc[a].Lf.canvas);lc[a]?.Lf.canvas&&(lc[a].Lf.canvas.Qf=void 0);lc[a]=null;M=12288;vc==b&&(vc=0);return 1},de:(a,b)=>{if(a!=62E3)return M=12296,0;if(b!=62006)return M=
12301,1;wc==b&&(wc=0);xc==b&&(xc=0);M=12288;return 1},Ve:(a,b,c,d)=>{if(a!=62E3)return M=12296,0;if(b!=62002)return M=12293,0;if(!d)return M=12300,0;M=12288;switch(c){case 12320:return q[d>>2]=O.alpha?32:24,1;case 12321:return q[d>>2]=O.alpha?8:0,1;case 12322:return q[d>>2]=8,1;case 12323:return q[d>>2]=8,1;case 12324:return q[d>>2]=8,1;case 12325:return q[d>>2]=O.depth?24:0,1;case 12326:return q[d>>2]=O.stencil?8:0,1;case 12327:return q[d>>2]=12344,1;case 12328:return q[d>>2]=62002,1;case 12329:return q[d>>
2]=0,1;case 12330:return q[d>>2]=4096,1;case 12331:return q[d>>2]=16777216,1;case 12332:return q[d>>2]=4096,1;case 12333:return q[d>>2]=0,1;case 12334:return q[d>>2]=0,1;case 12335:return q[d>>2]=12344,1;case 12337:return q[d>>2]=O.antialias?4:0,1;case 12338:return q[d>>2]=O.antialias?1:0,1;case 12339:return q[d>>2]=4,1;case 12340:return q[d>>2]=12344,1;case 12341:case 12342:case 12343:return q[d>>2]=-1,1;case 12345:case 12346:return q[d>>2]=0,1;case 12347:return q[d>>2]=0,1;case 12348:return q[d>>
2]=1;case 12349:case 12350:return q[d>>2]=0,1;case 12351:return q[d>>2]=12430,1;case 12352:return q[d>>2]=4,1;case 12354:return q[d>>2]=0,1;default:return M=12292,0}},i:a=>{M=12288;return a!=0&&a!=1?0:62E3},xc:()=>M,aa:(a,b,c)=>{if(a!=62E3)return M=12296,0;b&&(q[b>>2]=1);c&&(q[c>>2]=4);uc=!0;M=12288;return 1},Ud:(a,b,c,d)=>{if(a!=62E3)return M=12296,0;if(d!=0&&d!=62004)return M=12294,0;if(c!=0&&c!=62006||b!=0&&b!=62006)return M=12301,0;mc(d?zc:null);vc=d;xc=b;wc=c;M=12288;return 1},Ic:(a,b)=>{if(a!=
62E3)return M=12296,0;M=12288;if(yc[b])return yc[b];switch(b){case 12371:a=Sc("Emscripten");break;case 12372:a=Sc("1.4 Emscripten EGL");break;case 12373:a=Sc("");break;case 12429:a=Sc("OpenGL_ES");break;default:return M=12300,0}return yc[b]=a},Jd:()=>{if(uc)if(P)if(P.isContextLost())M=12302;else return M=12288,1;else M=12290;else M=12289;return 0},yd:(a,b)=>{if(a!=62E3)return M=12296,0;b==0?md(0,0):md(1,b);M=12288;return 1},R:a=>{if(a!=62E3)return M=12296,0;xc=wc=vc=0;uc=!1;M=12288;return 1},cd:()=>
{M=12288;return 1},nd:()=>{M=12288;return 1},b:(a,b,c)=>{b=od(b,c);return te[a](...b)},bc:(a,b,c)=>{b=od(b,c);return te[a](...b)},gf:()=>{hd();Uc=null},F:()=>Date.now(),Aa:()=>{if(!V.fullscreenEnabled())return-1;rd(Hd);var a=vd[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ib:()=>{rd(Id);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},ff:a=>{Ga=!1;
Vb=0;pa=a;Yb(a)},d:()=>globalThis.devicePixelRatio??1,a:(a,b,c)=>{a=X(a);if(!a)return-4;a=Gd(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},g:()=>performance.now(),mc:(a,b)=>{q[a>>2]=screen.width;q[b>>2]=screen.height},ga:a=>P.activeTexture(a),fa:(a,b)=>{P.attachShader(Q[a],R[b])},wa:(a,b)=>{P.Cf.beginQueryEXT(a,Hc[b])},hc:a=>P.beginTransformFeedback(a),ea:(a,b,c)=>{P.bindAttribLocation(Q[a],b,c?B(z,c):"")},da:(a,b)=>{a==35051?P.bg=b:a==35052&&(P.Ef=b);P.bindBuffer(a,Cc[b])},ec:(a,b,c)=>{P.bindBufferBase(a,
b,Cc[c])},fc:(a,b,c,d,e)=>{P.bindBufferRange(a,b,Cc[c],d,e)},ca:(a,b)=>{P.bindFramebuffer(a,Dc[b])},ba:(a,b)=>{P.bindRenderbuffer(a,Ec[b])},mb:(a,b)=>{P.bindSampler(a,S[b])},$:(a,b)=>{P.bindTexture(a,Fc[b])},fb:(a,b)=>{P.bindTransformFeedback(a,Ic[b])},oa:a=>{P.bindVertexArray(Gc[a])},_:(a,b,c,d)=>P.blendColor(a,b,c,d),Z:a=>P.blendEquation(a),Y:(a,b)=>P.blendEquationSeparate(a,b),X:(a,b)=>P.blendFunc(a,b),W:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),lc:(a,b,c,d,e,g,h,l,m,p)=>P.blitFramebuffer(a,b,c,
d,e,g,h,l,m,p),V:(a,b,c,d)=>{c&&b?P.bufferData(a,z,d,c,b):P.bufferData(a,b,d)},U:(a,b,c,d)=>{var e=z;c&&P.bufferSubData(a,b,e,d,c)},T:a=>P.checkFramebufferStatus(a),S:a=>P.clear(a),Hb:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),Jb:(a,b,c)=>{P.clearBufferfv(a,b,u,c>>2)},Lb:(a,b,c)=>{P.clearBufferiv(a,b,q,c>>2)},Kb:(a,b,c)=>{P.clearBufferuiv(a,b,y,c>>2)},Q:(a,b,c,d)=>P.clearColor(a,b,c,d),P:a=>P.clearDepth(a),O:a=>P.clearStencil(a),vb:(a,b,c)=>{c=Number(c);return P.clientWaitSync(Jc[a],b,c)},Lc:(a,b)=>{P.Wg.clipControlEXT(a,
b)},N:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},M:a=>{P.compileShader(R[a])},L:(a,b,c,d,e,g,h,l)=>{P.Ef||!h?P.compressedTexImage2D(a,b,c,d,e,g,h,l):P.compressedTexImage2D(a,b,c,d,e,g,z,l,h)},uc:(a,b,c,d,e,g,h,l,m)=>{P.Ef?P.compressedTexImage3D(a,b,c,d,e,g,h,l,m):P.compressedTexImage3D(a,b,c,d,e,g,h,z,m,l)},K:(a,b,c,d,e,g,h,l,m)=>{P.Ef||!l?P.compressedTexSubImage2D(a,b,c,d,e,g,h,l,m):P.compressedTexSubImage2D(a,b,c,d,e,g,h,z,m,l)},tc:(a,b,c,d,e,g,h,l,m,p,r)=>{P.Ef?P.compressedTexSubImage3D(a,b,c,d,
e,g,h,l,m,p,r):P.compressedTexSubImage3D(a,b,c,d,e,g,h,l,m,z,r,p)},Fb:(a,b,c,d,e)=>P.copyBufferSubData(a,b,c,d,e),J:(a,b,c,d,e,g,h,l)=>P.copyTexImage2D(a,b,c,d,e,g,h,l),I:(a,b,c,d,e,g,h,l)=>P.copyTexSubImage2D(a,b,c,d,e,g,h,l),vc:(a,b,c,d,e,g,h,l,m)=>P.copyTexSubImage3D(a,b,c,d,e,g,h,l,m),H:()=>{var a=Oc(Q),b=P.createProgram();b.name=a;b.Yf=b.Wf=b.Xf=0;b.ug=1;Q[a]=b;return a},df:a=>{var b=Oc(R);R[b]=P.createShader(a);return b},cf:a=>P.cullFace(a),bf:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2],
e=Cc[d];e&&(P.deleteBuffer(e),e.name=0,Cc[d]=null,d==P.bg&&(P.bg=0),d==P.Ef&&(P.Ef=0))}},af:(a,b)=>{for(var c=0;c<a;++c){var d=q[b+c*4>>2],e=Dc[d];e&&(P.deleteFramebuffer(e),e.name=0,Dc[d]=null)}},$e:a=>{if(a){var b=Q[a];b?(P.deleteProgram(b),b.name=0,Q[a]=null):T||=1281}},ya:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2],e=Hc[d];e&&(P.Cf.deleteQueryEXT(e),Hc[d]=null)}},_e:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2],e=Ec[d];e&&(P.deleteRenderbuffer(e),e.name=0,Ec[d]=null)}},ob:(a,b)=>{for(var c=
0;c<a;c++){var d=q[b+c*4>>2],e=S[d];e&&(P.deleteSampler(e),e.name=0,S[d]=null)}},Ze:a=>{if(a){var b=R[a];b?(P.deleteShader(b),R[a]=null):T||=1281}},wb:a=>{if(a){var b=Jc[a];b?(P.deleteSync(b),b.name=0,Jc[a]=null):T||=1281}},Ye:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2],e=Fc[d];e&&(P.deleteTexture(e),e.name=0,Fc[d]=null)}},eb:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2],e=Ic[d];e&&(P.deleteTransformFeedback(e),e.name=0,Ic[d]=null)}},na:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+c*4>>2];P.deleteVertexArray(Gc[d]);
Gc[d]=null}},Xe:a=>P.depthFunc(a),We:a=>{P.depthMask(!!a)},Ue:(a,b)=>P.depthRange(a,b),Te:(a,b)=>{P.detachShader(Q[a],R[b])},Se:a=>P.disable(a),Re:a=>{P.disableVertexAttribArray(a)},Qe:(a,b,c)=>{P.drawArrays(a,b,c)},ja:Jd,Fc:Jd,Gc:Jd,Ra:Jd,Bc:Ld,ka:Ld,Pe:(a,b,c,d)=>{P.drawElements(a,b,c,d)},ia:Md,Cc:Md,Dc:Md,Ec:Md,zc:(a,b,c,d,e,g)=>{P.drawElements(a,d,e,g)},Oe:a=>P.enable(a),Ne:a=>{P.enableVertexAttribArray(a)},va:a=>{P.Cf.endQueryEXT(a)},gc:()=>P.endTransformFeedback(),yb:(a,b)=>(a=P.fenceSync(a,
b))?(b=Oc(Jc),a.name=b,Jc[b]=a,b):0,Me:()=>P.finish(),Le:()=>P.flush(),Je:(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,Ec[d])},Ie:(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,Fc[d],e)},jc:(a,b,c,d,e)=>{P.framebufferTextureLayer(a,b,Fc[c],d,e)},He:a=>P.frontFace(a),Ge:(a,b)=>{Pc(a,b,"createBuffer",Cc)},Ee:(a,b)=>{Pc(a,b,"createFramebuffer",Dc)},za:(a,b)=>{for(var c=0;c<a;c++){var d=P.Cf.createQueryEXT();if(!d){for(T||=1282;c<a;)q[b+c++*4>>2]=0;break}var e=Oc(Hc);d.name=e;Hc[e]=d;q[b+c*4>>2]=e}},De:(a,
b)=>{Pc(a,b,"createRenderbuffer",Ec)},pb:(a,b)=>{Pc(a,b,"createSampler",S)},Ce:(a,b)=>{Pc(a,b,"createTexture",Fc)},cb:(a,b)=>{Pc(a,b,"createTransformFeedback",Ic)},ma:(a,b)=>{Pc(a,b,"createVertexArray",Gc)},Fe:a=>P.generateMipmap(a),Be:(a,b,c,d,e,g,h)=>Nd("getActiveAttrib",a,b,c,d,e,g,h),Ae:(a,b,c,d,e,g,h)=>Nd("getActiveUniform",a,b,c,d,e,g,h),Ab:(a,b,c,d,e)=>{a=Q[a];if(a=P.getActiveUniformBlockName(a,b))e&&c>0?(c=C(a,z,e,c),d&&(q[d>>2]=c)):d&&(q[d>>2]=0)},Bb:(a,b,c,d)=>{if(d)if(a=Q[a],c==35393)q[d>>
2]=P.getActiveUniformBlockName(a,b).length+1;else{if(a=P.getActiveUniformBlockParameter(a,b,c),a!==null)if(c==35395)for(c=0;c<a.length;c++)q[d+c*4>>2]=a[c];else q[d>>2]=a}else T||=1281},Db:(a,b,c,d,e)=>{if(e)if(b>0&&c==0)T||=1281;else{a=Q[a];for(var g=[],h=0;h<b;h++)g.push(q[c+h*4>>2]);if(a=P.getActiveUniforms(a,g,d))for(b=a.length,h=0;h<b;h++)q[e+h*4>>2]=a[h]}else T||=1281},ye:(a,b,c,d)=>{a=P.getAttachedShaders(Q[a]);var e=a.length;e>b&&(e=b);q[c>>2]=e;for(b=0;b<e;++b)q[d+b*4>>2]=R.indexOf(a[b])},
xe:(a,b)=>P.getAttribLocation(Q[a],b?B(z,b):""),we:(a,b)=>Qd(a,b,4),qb:(a,b,c)=>{c?Od(c,P.getBufferParameter(a,b)):T||=1281},ve:(a,b,c)=>{c?q[c>>2]=P.getBufferParameter(a,b):T||=1281},ue:()=>{var a=P.getError()||T;T=0;return a},te:(a,b)=>Qd(a,b,2),Ub:(a,b)=>P.getFragDataLocation(Q[a],b?B(z,b):""),se:(a,b,c,d)=>{a=P.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;q[d>>2]=a},rb:(a,b,c)=>Rd(a,b,c,1),tb:(a,b)=>{Qd(a,b,1)},ic:(a,b,c)=>Rd(a,
b,c,0),re:(a,b)=>Qd(a,b,0),Ta:(a,b,c,d,e)=>{if(d<0)T||=1281;else if(e){if(a=P.getInternalformatParameter(a,b,c),a!==null)for(b=0;b<a.length&&b<d;++b)q[e+b*4>>2]=a[b]}else T||=1281},_a:()=>{T||=1282},pe:(a,b,c,d)=>{a=P.getProgramInfoLog(Q[a]);a===null&&(a="(unknown error)");b=b>0&&d?C(a,z,d,b):0;c&&(q[c>>2]=b)},qe:(a,b,c)=>{if(c)if(a>=Bc)T||=1281;else if(a=Q[a],b==35716)a=P.getProgramInfoLog(a),a===null&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(b==35719){if(!a.Yf){var d=P.getProgramParameter(a,
35718);for(b=0;b<d;++b)a.Yf=Math.max(a.Yf,P.getActiveUniform(a,b).name.length+1)}q[c>>2]=a.Yf}else if(b==35722){if(!a.Wf)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.Wf=Math.max(a.Wf,P.getActiveAttrib(a,b).name.length+1);q[c>>2]=a.Wf}else if(b==35381){if(!a.Xf)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.Xf=Math.max(a.Xf,P.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.Xf}else q[c>>2]=P.getProgramParameter(a,b);else T||=1281},qa:Sd,sa:Td,pa:Sd,ra:Td,ta:(a,b,c)=>{c?q[c>>2]=P.Cf.getQueryEXT(a,
b):T||=1281},ne:(a,b,c)=>{c?q[c>>2]=P.getRenderbufferParameter(a,b):T||=1281},gb:(a,b,c)=>{c?u[c>>2]=P.getSamplerParameter(S[a],b):T||=1281},hb:(a,b,c)=>{c?q[c>>2]=P.getSamplerParameter(S[a],b):T||=1281},le:(a,b,c,d)=>{a=P.getShaderInfoLog(R[a]);a===null&&(a="(unknown error)");b=b>0&&d?C(a,z,d,b):0;c&&(q[c>>2]=b)},ke:(a,b,c,d)=>{a=P.getShaderPrecisionFormat(a,b);q[c>>2]=a.rangeMin;q[c+4>>2]=a.rangeMax;q[d>>2]=a.precision},je:(a,b,c,d)=>{if(a=P.getShaderSource(R[a]))b=b>0&&d?C(a,z,d,b):0,c&&(q[c>>
2]=b)},me:(a,b,c)=>{c?b==35716?(a=P.getShaderInfoLog(R[a]),a===null&&(a="(unknown error)"),q[c>>2]=a?a.length+1:0):b==35720?(a=P.getShaderSource(R[a]),q[c>>2]=a?a.length+1:0):q[c>>2]=P.getShaderParameter(R[a],b):T||=1281},ie:a=>{var b=Kc[a];if(!b){switch(a){case 7939:b=Sc(Pd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=P.getParameter(a))||(T||=1280);b=b?Sc(b):0;break;case 7938:b=Sc(`OpenGL ES 3.0 (${P.getParameter(7938)})`);break;case 35724:b=P.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Sc(b);break;default:T||=1280}Kc[a]=b}return b},Gb:(a,b)=>{if(Rc.version<2)return T||=1282,0;var c=Lc[a];if(c)return b<0||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Pd().map(Sc),c=Lc[a]=c,b<0||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},sb:(a,b,c,d,e)=>{c<0?T||=1281:e?(a=P.getSyncParameter(Jc[a],b),a!==null&&(q[e>>2]=a,d&&(q[d>>2]=1))):T||=1281},he:(a,b,c)=>{c?u[c>>2]=P.getTexParameter(a,b):
T||=1281},ge:(a,b,c)=>{c?q[c>>2]=P.getTexParameter(a,b):T||=1281},cc:(a,b,c,d,e,g,h)=>{a=Q[a];if(a=P.getTransformFeedbackVarying(a,b))h&&c>0?(c=C(a.name,z,h,c),d&&(q[d>>2]=c)):d&&(q[d>>2]=0),e&&(q[e>>2]=a.size),g&&(q[g>>2]=a.type)},Cb:(a,b)=>P.getUniformBlockIndex(Q[a],b?B(z,b):""),Eb:(a,b,c,d)=>{if(d)if(b>0&&(c==0||d==0))T||=1281;else{a=Q[a];for(var e=[],g=0;g<b;g++)e.push(Ub(y[c+g*4>>2]));if(a=P.getUniformIndices(a,e))for(b=a.length,g=0;g<b;g++)q[d+g*4>>2]=a[g]}else T||=1281},ce:(a,b)=>{b=b?B(z,
b):"";if(a=Q[a]){Vd(a);var c=a.Sf,d=0,e=b,g=Ud(b);g>0&&(d=b.slice(g+1),d=parseInt(d)>>>0,e=b.slice(0,g));if((g=a.Lg[e])&&d<g[0]&&(d+=g[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else T||=1281;return-1},fe:(a,b,c)=>{Wd(a,b,c,2)},ee:(a,b,c)=>{Wd(a,b,c,0)},Vb:(a,b,c)=>Wd(a,b,c,0),$b:Yd,_b:Yd,$d:(a,b,c)=>{c?q[c>>2]=P.getVertexAttribOffset(a,b):T||=1281},be:(a,b,c)=>{Xd(a,b,c,2)},ae:(a,b,c)=>{Xd(a,b,c,5)},_d:(a,b)=>P.hint(a,b),Xa:(a,b,c)=>{for(var d=Kd[b],e=0;e<b;e++)d[e]=q[c+e*4>>2];P.invalidateFramebuffer(a,
d)},Wa:(a,b,c,d,e,g,h)=>{for(var l=Kd[b],m=0;m<b;m++)l[m]=q[c+m*4>>2];P.invalidateSubFramebuffer(a,l,d,e,g,h)},Zd:a=>(a=Cc[a])?P.isBuffer(a):0,Yd:a=>P.isEnabled(a),Xd:a=>(a=Dc[a])?P.isFramebuffer(a):0,Wd:a=>(a=Q[a])?P.isProgram(a):0,xa:a=>(a=Hc[a])?P.Cf.isQueryEXT(a):0,Vd:a=>(a=Ec[a])?P.isRenderbuffer(a):0,nb:a=>(a=S[a])?P.isSampler(a):0,Td:a=>(a=R[a])?P.isShader(a):0,xb:a=>P.isSync(Jc[a]),Sd:a=>(a=Fc[a])?P.isTexture(a):0,bb:a=>P.isTransformFeedback(Ic[a]),la:a=>(a=Gc[a])?P.isVertexArray(a):0,Rd:a=>
P.lineWidth(a),Qd:a=>{a=Q[a];P.linkProgram(a);a.Sf=0;a.Lg={}},ab:()=>P.pauseTransformFeedback(),Pd:(a,b)=>{a==3317?Mc=b:a==3314&&(Nc=b);P.pixelStorei(a,b)},Kc:(a,b)=>{P.ph.polygonModeWEBGL(a,b)},Od:(a,b)=>P.polygonOffset(a,b),Mc:(a,b,c)=>{P.Xg.polygonOffsetClampEXT(a,b,c)},Za:()=>{T||=1280},Ya:()=>{T||=1280},ua:(a,b)=>{P.Cf.queryCounterEXT(Hc[a],b)},Ac:a=>P.readBuffer(a),Nd:(a,b,c,d,e,g,h)=>{if(P.bg)P.readPixels(a,b,c,d,e,g,h);else{var l=Zd(g);h>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);P.readPixels(a,
b,c,d,e,g,l,h)}},Md:()=>{},Ld:(a,b,c,d)=>P.renderbufferStorage(a,b,c,d),kc:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),$a:()=>P.resumeTransformFeedback(),Kd:(a,b)=>{P.sampleCoverage(a,!!b)},jb:(a,b,c)=>{P.samplerParameterf(S[a],b,c)},ib:(a,b,c)=>{P.samplerParameterf(S[a],b,u[c>>2])},lb:(a,b,c)=>{P.samplerParameteri(S[a],b,c)},kb:(a,b,c)=>{P.samplerParameteri(S[a],b,q[c>>2])},Id:(a,b,c,d)=>P.scissor(a,b,c,d),Hd:()=>{T||=1280},Gd:(a,b,c,d)=>{for(var e="",g=0;g<b;++g)e+=Ub(y[c+g*4>>2],d?
y[d+g*4>>2]:void 0);P.shaderSource(R[a],e)},Fd:(a,b,c)=>P.stencilFunc(a,b,c),Ed:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),Dd:a=>P.stencilMask(a),Cd:(a,b)=>P.stencilMaskSeparate(a,b),Bd:(a,b,c)=>P.stencilOp(a,b,c),Ad:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),zd:(a,b,c,d,e,g,h,l,m)=>{if(P.Ef)P.texImage2D(a,b,c,d,e,g,h,l,m);else if(m){var p=Zd(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,g,h,l,p,m)}else p=m?$d(l,h,d,e,m):null,P.texImage2D(a,b,c,d,e,g,h,l,p)},yc:(a,b,c,d,e,g,h,l,m,
p)=>{if(P.Ef)P.texImage3D(a,b,c,d,e,g,h,l,m,p);else if(p){var r=Zd(m);P.texImage3D(a,b,c,d,e,g,h,l,m,r,p>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,g,h,l,m,null)},xd:(a,b,c)=>P.texParameterf(a,b,c),wd:(a,b,c)=>{P.texParameterf(a,b,u[c>>2])},vd:(a,b,c)=>P.texParameteri(a,b,c),ud:(a,b,c)=>{P.texParameteri(a,b,q[c>>2])},Va:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),Ua:(a,b,c,d,e,g)=>P.texStorage3D(a,b,c,d,e,g),td:(a,b,c,d,e,g,h,l,m)=>{if(P.Ef)P.texSubImage2D(a,b,c,d,e,g,h,l,m);else if(m){var p=
Zd(l);P.texSubImage2D(a,b,c,d,e,g,h,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=m?$d(l,h,e,g,m):null,P.texSubImage2D(a,b,c,d,e,g,h,l,m)},wc:(a,b,c,d,e,g,h,l,m,p,r)=>{if(P.Ef)P.texSubImage3D(a,b,c,d,e,g,h,l,m,p,r);else if(r){var v=Zd(p);P.texSubImage3D(a,b,c,d,e,g,h,l,m,p,v,r>>>31-Math.clz32(v.BYTES_PER_ELEMENT))}else P.texSubImage3D(a,b,c,d,e,g,h,l,m,p,null)},dc:(a,b,c,d)=>{a=Q[a];for(var e=[],g=0;g<b;g++)e.push(Ub(y[c+g*4>>2]));P.transformFeedbackVaryings(a,e,d)},sd:(a,b)=>{P.uniform1f(Y(P.tf,
a),b)},rd:(a,b,c)=>{b&&P.uniform1fv(Y(P.tf,a),u,c>>2,b)},qd:(a,b)=>{P.uniform1i(Y(P.tf,a),b)},pd:(a,b,c)=>{b&&P.uniform1iv(Y(P.tf,a),q,c>>2,b)},Tb:(a,b)=>{P.uniform1ui(Y(P.tf,a),b)},Pb:(a,b,c)=>{b&&P.uniform1uiv(Y(P.tf,a),y,c>>2,b)},od:(a,b,c)=>{P.uniform2f(Y(P.tf,a),b,c)},md:(a,b,c)=>{b&&P.uniform2fv(Y(P.tf,a),u,c>>2,b*2)},ld:(a,b,c)=>{P.uniform2i(Y(P.tf,a),b,c)},kd:(a,b,c)=>{b&&P.uniform2iv(Y(P.tf,a),q,c>>2,b*2)},Sb:(a,b,c)=>{P.uniform2ui(Y(P.tf,a),b,c)},Ob:(a,b,c)=>{b&&P.uniform2uiv(Y(P.tf,a),
y,c>>2,b*2)},jd:(a,b,c,d)=>{P.uniform3f(Y(P.tf,a),b,c,d)},id:(a,b,c)=>{b&&P.uniform3fv(Y(P.tf,a),u,c>>2,b*3)},hd:(a,b,c,d)=>{P.uniform3i(Y(P.tf,a),b,c,d)},gd:(a,b,c)=>{b&&P.uniform3iv(Y(P.tf,a),q,c>>2,b*3)},Rb:(a,b,c,d)=>{P.uniform3ui(Y(P.tf,a),b,c,d)},Nb:(a,b,c)=>{b&&P.uniform3uiv(Y(P.tf,a),y,c>>2,b*3)},fd:(a,b,c,d,e)=>{P.uniform4f(Y(P.tf,a),b,c,d,e)},ed:(a,b,c)=>{b&&P.uniform4fv(Y(P.tf,a),u,c>>2,b*4)},dd:(a,b,c,d,e)=>{P.uniform4i(Y(P.tf,a),b,c,d,e)},bd:(a,b,c)=>{b&&P.uniform4iv(Y(P.tf,a),q,c>>2,
b*4)},Qb:(a,b,c,d,e)=>{P.uniform4ui(Y(P.tf,a),b,c,d,e)},Mb:(a,b,c)=>{b&&P.uniform4uiv(Y(P.tf,a),y,c>>2,b*4)},zb:(a,b,c)=>{a=Q[a];P.uniformBlockBinding(a,b,c)},ad:(a,b,c,d)=>{b&&P.uniformMatrix2fv(Y(P.tf,a),!!c,u,d>>2,b*4)},sc:(a,b,c,d)=>{b&&P.uniformMatrix2x3fv(Y(P.tf,a),!!c,u,d>>2,b*6)},qc:(a,b,c,d)=>{b&&P.uniformMatrix2x4fv(Y(P.tf,a),!!c,u,d>>2,b*8)},$c:(a,b,c,d)=>{b&&P.uniformMatrix3fv(Y(P.tf,a),!!c,u,d>>2,b*9)},rc:(a,b,c,d)=>{b&&P.uniformMatrix3x2fv(Y(P.tf,a),!!c,u,d>>2,b*6)},oc:(a,b,c,d)=>{b&&
P.uniformMatrix3x4fv(Y(P.tf,a),!!c,u,d>>2,b*12)},_c:(a,b,c,d)=>{b&&P.uniformMatrix4fv(Y(P.tf,a),!!c,u,d>>2,b*16)},pc:(a,b,c,d)=>{b&&P.uniformMatrix4x2fv(Y(P.tf,a),!!c,u,d>>2,b*8)},nc:(a,b,c,d)=>{b&&P.uniformMatrix4x3fv(Y(P.tf,a),!!c,u,d>>2,b*12)},Zc:a=>{a=Q[a];P.useProgram(a);P.tf=a},Yc:a=>{P.validateProgram(Q[a])},Xc:(a,b)=>P.vertexAttrib1f(a,b),Wc:(a,b)=>{P.vertexAttrib1f(a,u[b>>2])},Vc:(a,b,c)=>P.vertexAttrib2f(a,b,c),Uc:(a,b)=>{P.vertexAttrib2f(a,u[b>>2],u[b+4>>2])},Sc:(a,b,c,d)=>P.vertexAttrib3f(a,
b,c,d),Rc:(a,b)=>{P.vertexAttrib3f(a,u[b>>2],u[b+4>>2],u[b+8>>2])},Qc:(a,b,c,d,e)=>P.vertexAttrib4f(a,b,c,d,e),Pc:(a,b)=>{P.vertexAttrib4f(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},ha:ae,Hc:ae,Jc:ae,Sa:ae,Zb:(a,b,c,d,e)=>P.vertexAttribI4i(a,b,c,d,e),Xb:(a,b)=>{P.vertexAttribI4i(a,q[b>>2],q[b+4>>2],q[b+8>>2],q[b+12>>2])},Yb:(a,b,c,d,e)=>P.vertexAttribI4ui(a,b,c,d,e),Wb:(a,b)=>{P.vertexAttribI4ui(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},ac:(a,b,c,d,e)=>{P.vertexAttribIPointer(a,b,c,d,e)},Oc:(a,b,
c,d,e,g)=>{P.vertexAttribPointer(a,b,c,!!d,e,g)},Nc:(a,b,c,d)=>P.viewport(a,b,c,d),ub:(a,b,c)=>{c=Number(c);P.waitSync(Jc[a],b,c)},f:()=>0,Ba:(a,b,c)=>be(a,{og:q[c>>2],ag:q[c+4>>2],Yg:q[c+8>>2],Tg:b,Uf:q[c+12>>2],yg:q[c+16>>2]}),G:(a,b)=>{a=X(a);return a?a.requestPointerLock?sd()?Id(a):b?(qd(Id,2,[a]),1):-2:-1:-4},Fa:()=>{n("OOM")},j:(a,b,c)=>typeof onbeforeunload=="undefined"?-1:c!==1?-5:ce(a,b),v:(a,b,c,d)=>de(a,b,c,d,12,"blur"),c:Bd,h:(a,b,c)=>{a=X(a);if(!a)return-4;a.style.width=b+"px";a.style.height=
c+"px";return 0},w:(a,b,c,d)=>de(a,b,c,d,13,"focus"),m:(a,b,c,d)=>{if(!V.fullscreenEnabled())return-1;a=X(a);if(!a)return-4;ee(a,b,c,d,"webkitfullscreenchange");return ee(a,b,c,d,"fullscreenchange")},db:(a,b,c)=>ge()?-1:fe(a,b,c,26,"gamepadconnected"),Da:(a,b,c)=>ge()?-1:fe(a,b,c,27,"gamepaddisconnected"),p:(a,b,c,d)=>he(a,b,c,d,2,"keydown"),n:(a,b,c,d)=>he(a,b,c,d,1,"keypress"),o:(a,b,c,d)=>he(a,b,c,d,3,"keyup"),B:(a,b,c,d)=>je(a,b,c,d,5,"mousedown"),z:(a,b,c,d)=>je(a,b,c,d,33,"mouseenter"),y:(a,
b,c,d)=>je(a,b,c,d,34,"mouseleave"),D:(a,b,c,d)=>je(a,b,c,d,8,"mousemove"),A:(a,b,c,d)=>je(a,b,c,d,6,"mouseup"),q:(a,b,c,d)=>document.body?.requestPointerLock?(a=X(a))?ke(a,b,c,d):-4:-1,l:(a,b,c,d)=>le(a,b,c,d),r:(a,b,c,d)=>me(a,b,c,d,25,"touchcancel"),t:(a,b,c,d)=>me(a,b,c,d,23,"touchend"),s:(a,b,c,d)=>me(a,b,c,d,24,"touchmove"),u:(a,b,c,d)=>me(a,b,c,d,22,"touchstart"),k:(a,b,c)=>vd[1]?ne(a,b,c):-4,x:(a,b,c,d)=>(a=X(a))?typeof a.onwheel!="undefined"?oe(a,b,c,d):-1:-4,Ca:a=>document.title=a?B(z,a):
"",e:()=>{n("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},La:(a,b)=>{var c=0,d=0,e;for(e of se()){var g=b+c;y[a+d>>2]=g;c+=C(e,z,g,Infinity)+1;d+=4}return 0},Ma:(a,b)=>{var c=se();y[a>>2]=c.length;a=0;for(var d of c)a+=Ta(d)+1;y[b>>2]=a;return 0},C:function(a){try{var b=yb(a);Kb(b);return 0}catch(c){if(typeof Tb=="undefined"||c.name!=="ErrnoError")throw c;return c.Ff}},Oa:function(a,b,c,d){try{a:{var e=yb(a);a=b;for(var g,h=b=0;h<
c;h++){var l=y[a>>2],m=y[a+4>>2];a+=8;var p=e,r=l,v=m,w=g,G=t;if(v<0||w<0)throw new D(28);if(p.fd===null)throw new D(8);if((p.flags&2097155)===1)throw new D(8);if(H(p.node.mode))throw new D(31);if(!p.rf.read)throw new D(28);var E=typeof w!="undefined";if(!E)w=p.position;else if(!p.seekable)throw new D(70);var K=p.rf.read(p,G,r,v,w);E||(p.position+=K);var J=K;if(J<0){var I=-1;break a}b+=J;if(J<m)break;typeof g!="undefined"&&(g+=J)}I=b}y[d>>2]=I;return 0}catch(Z){if(typeof Tb=="undefined"||Z.name!==
"ErrnoError")throw Z;return Z.Ff}},Ka:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=yb(a);Lb(e,b,c);wa[d>>3]=BigInt(e.position);e.ig&&b===0&&c===0&&(e.ig=null);return 0}catch(g){if(typeof Tb=="undefined"||g.name!=="ErrnoError")throw g;return g.Ff}},Na:function(a,b,c,d){try{a:{var e=yb(a);a=b;for(var g,h=b=0;h<c;h++){var l=y[a>>2],m=y[a+4>>2];a+=8;var p=Mb(e,t,l,m,g);if(p<0){var r=-1;break a}b+=p;if(p<m)break;typeof g!="undefined"&&(g+=p)}r=
b}y[d>>2]=r;return 0}catch(v){if(typeof Tb=="undefined"||v.name!=="ErrnoError")throw v;return v.Ff}},Ha:Yb};function ye(a=[]){var b=ue;a.unshift(ea);var c=a.length,d=wd((c+1)*4),e=d,g;for(g of a)y[e>>2]=xd(g),e+=4;y[e>>2]=0;try{var h=b(c,d);pa=h;Yb(h)}catch(l){Xb(l)}}
function ze(a=da){function b(){f.calledRun=!0;if(!oa){if(!f.noFSInit&&!pb){var c,d;pb=!0;c??=f.stdin;d??=f.stdout;e??=f.stderr;c?Qb("/dev","stdin",c):Gb("/dev/tty","/dev/stdin");d?Qb("/dev","stdout",null,d):Gb("/dev/tty","/dev/stdout");e?Qb("/dev","stderr",null,e):Gb("/dev/tty1","/dev/stderr");Jb("/dev/stdin",0);Jb("/dev/stdout",1);Jb("/dev/stderr",1)}Ae.jf();qb=!1;f.onRuntimeInitialized?.();f.noInitialRun||ye(a);if(f.postRun)for(typeof f.postRun=="function"&&(f.postRun=[f.postRun]);f.postRun.length;){var e=
f.postRun.shift();za.push(e)}ya(za)}}if(Ca>0)Da=ze;else{if(f.preRun)for(typeof f.preRun=="function"&&(f.preRun=[f.preRun]);f.preRun.length;)Ba();ya(Aa);Ca>0?Da=ze:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}var Ae;
(async function(){function a(c){c=Ae=c.exports;ue=f._main=c.kf;U=c.lf;ve=c.nf;zd=c.of;wd=c.pf;yd=c.qf;we=c.hf;Ia=c.mf;c=we.buffer;t=new Int8Array(c);va=new Int16Array(c);z=new Uint8Array(c);xa=new Uint16Array(c);q=new Int32Array(c);y=new Uint32Array(c);u=new Float32Array(c);x=new Float64Array(c);wa=new BigInt64Array(c);new BigUint64Array(c);Ea("wasm-instantiate");return Ae}Fa("wasm-instantiate");var b={a:xe};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});qa??=
f.locateFile?f.locateFile("index.wasm",ia):ia+"index.wasm";return function(c){return a(c.instance)}(await ta(b))})();ze();
